[keys]

[addresses]
validator-6 = "atest1v4ehgw36gymnvden8yersvpn8qe5vs33xymnwd298pz5vd69gscy2vfsxdqnxd33gcurwv33t7vsac"
BTC = "atest1v4ehgw36xdzryve5gsc52veeg5cnsv2yx5eygvp38qcrvd29xy6rys6p8yc5xvp4xfpy2v694wgwcp"
validator-7 = "atest1v4ehgw36xce5ywp3g5mnxvej8ycnx3zxx56r2vpsx4zrwd3ng4qnxdpjxu6rs3zyxy65vvfhhjj828"
matchmaker-4 = "atest1v4ehgw36xymyz3f58qc5gv6rxcmyy3fsg5mrws3jxepr2335xsunsd33g4znqs2rxvcyzs3s47deg0"
matchmaker-10 = "atest1v4ehgw36xgmn2w2zg5unvv3jgcuyy334xfprz33nxyerwdpjxvenwv29gverjd3eg5u52s3kkzr39j"
validator-9 = "atest1v4ehgw36x3pyvs3cxqe5gdjy8yeyvwfexqenwdekgve5ydzzxvengdzpxdzns335gsmrgw2zxutm5j"
matchmaker-3 = "atest1v4ehgw36ggm5v3z9gycygven8ycngvjzg5m5vsfkx3z5zwf58qmnvse4gfqnjvfsxscrqsfez9nw8v"
validator-1 = "atest1v4ehgw36xprrsvehxuu5vdecgye5z3fexcunzs3hggerq33nxqcnjsjrg3qngs6rx4zrjsfngwvs0r"
ETH = "atest1v4ehgw36xqmr2d3nx3ryvd2xxgmrq33j8qcns33sxezrgv6zxdzrydjrxveygd2yxumrsdpsf9jc2p"
matchmaker-7 = "atest1v4ehgw36xap5ydjxg9zrss6yxfz5zwpngv6rzv2rx5ervvphxdrrvv3kx4q5z333gymnsdphf4zl4d"
validator-2 = "atest1v4ehgw368pzryvpkggmr2vehxcmnz3pnxc6nwsecxc65gdzrxgerzwzzx3q5zdzxx56rg32pygu5we"
Kartoffel = "atest1v4ehgw36gep5ysecxq6nyv3jg3zygv3e89qn2vp48pryxsf4xpznvve5gvmy23fs89pryvf5a6ht90"
matchmaker-9 = "atest1v4ehgw36xpryv3f4g3z5zw2989pyysfsxgcrzdp4g3zyxd3eg9q5xvejg56ngwf3x9qnzvjpr6zxng"
faucet = "atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3"
validator-3 = "atest1v4ehgw3689rrswpjg4zyzwf3x3pn2v2rx4znqs3ngseyysfkxum5zdfkxseyxwfjxvcrsdfknf2qp2"
PosSlashPool = "atest1v9hx7w362pex7mmxyphkvgznw3skkefq2dkxzumgypgx7mmvyqszqgpqyqszqgpqyqszqgpqecxumt"
Schnitzel = "atest1v4ehgw36xue5xvf5xvuyzvpjx5un2v3k8qeyvd3cxdqns32p89rrxd6xx9zngvpegccnzs699rdnnt"
XAN = "atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5"
validator-5 = "atest1v4ehgw36x3pnqdjyx3prjsjyx3z5ywpsxdrr2vzpx5m5xvenxger2dp58y652v29xceygs6xeeunr6"
validator-4 = "atest1v4ehgw368qeyv3fjxsmrz32yxdrygd2zx4prwv6ygfrrgvfhgscnvv6rx5cnqwf5x9rrjw2x03kky2"
matchmaker-2 = "atest1v4ehgw36x9qnwde38ycrqd3cg5erxd69xgcrvdfh8prygwfcxezyz3jyxgcyxv2zx4ryy3jy3qdmsu"
matchmaker-8 = "atest1v4ehgw36xepnws6x89q5zs3exqurgs6xg4rrgvec8ymryse489ryvv34xaznwwpkxy6nsvzxfaxff6"
matchmaker-6 = "atest1v4ehgw36x4znzwzx8q65gv3sgs65gwpsxscnjd2zx5c5gwpkgeznzs34x9zygsecxfzrgdp56v4e56"
matchmaker-5 = "atest1v4ehgw368ycrgv6xg5erz32rx56nqsjzg3zyvdzzgy6n2djyxprygv2rxvcrjv34xpqnvvzyhq0gj4"
matchmaker-1 = "atest1v4ehgw36xfzy2sesxge5vsjrxg652vjpxqcrjs35g5er233kg9q5vwf5x9p5vwfeg9p5y32zrfl5vh"
DOT = "atest1v4ehgw36gg6nvs2zgfpyxsfjgc65yv6pxy6nwwfsxgungdzrggeyzv35gveyxsjyxymyz335hur2jn"
validator-8 = "atest1v4ehgw36ggmrjdjzx3pnwdjzxqurxvjxgcm5ydzrx5cn23fjxqcnzse5x5cnxd3nxvurwv3cquh96p"
validator-10 = "atest1v4ehgw36x5m5z3p3xu6y2vzx89p5gv2989z5x33cxyenjdfjg9rrgve48qenjd6zgs6y2vp3re58cj"
Apfel = "atest1v4ehgw36gfryydj9g3p5zv3kg9znyd358ycnzsfcggc5gvecgc6ygs2rxv6ry3zpg4zrwdfeumqcz9"
PoS = "atest1v9hx7w362pex7mmxyphkvgznw3skkefqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqq8ylv7"

[pkhs]
